### ISSUE TITLE
Story: Create and Configure GitHub Repository

### ISSUE THREAD

**Issue by Nicmanthecodeman** [Nicmanthecodeman/CMPG-323-Overview-25102737#2]
## User Story:

> As a **student**, 
> I want to **create and configure a GitHub Repository**, 
> so that I can **plan, manage and keep up to date with this semester's projects**

### Tasks (to be broken down further)

- [x] Create a repository named \'CMPG 323 Overview - \<add your student number>' <code>Priority: 1</code>
- [x] Create the following Milestones: <code>Priority: 2</code>
    - [x] Project 1 Submission: Deadline – 18 August
    - [x] Project 2 Submission: Deadline – 8 September
    - [x] Project 3 Submission: Deadline – 29 September
    - [x] Project 4 Submission: Deadline – 20 October
    - [x] Project 5 Submission: Deadline – 3 November
    - [x] Exam (POE) Submission: Deadline – 18 November
- [x] Create the following Labels: <code>Priority: 2</code>
    - [x]  Class
    - [x] Project
    - [x] Training
    - [x] \<any other labels you might find relevant>
